name: week_number
description: Adds extension method to get the week number from a date
version: 1.1.0
repository: https://github.com/sousyokunotomonokai/week_number
issue_tracker: https://github.com/sousyokunotomonokai/week_number/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ">=1.0.0"
  test: ">=1.10.0"
